services:
  aster:
    build:
      context: ./
      network: host
    environment:
      - "ASTER__APIS__DINGO__HOST=${ASTER__APIS__DINGO__HOST:-localhost}"
      - "ASTER__APIS__DINGO__PATH=${ASTER__APIS__DINGO__PATH:-}"
      - "ASTER__APIS__DINGO__PORT=${ASTER__APIS__DINGO__PORT:-10101}"
      - "ASTER__APIS__DINGO__SCHEME=${ASTER__APIS__DINGO__SCHEME:-http}"
      - "ASTER__APIS__ICANHAZDADJOKE__HOST=${ASTER__APIS__ICANHAZDADJOKE__HOST:-icanhazdadjoke.com}"
      - "ASTER__APIS__ICANHAZDADJOKE__PATH=${ASTER__APIS__ICANHAZDADJOKE__PATH:-}"
      - "ASTER__APIS__ICANHAZDADJOKE__PORT=${ASTER__APIS__ICANHAZDADJOKE__PORT:-}"
      - "ASTER__APIS__ICANHAZDADJOKE__SCHEME=${ASTER__APIS__ICANHAZDADJOKE__SCHEME:-https}"
      - "ASTER__APIS__PELICAN__HOST=${ASTER__APIS__PELICAN__HOST:-localhost}"
      - "ASTER__APIS__PELICAN__PATH=${ASTER__APIS__PELICAN__PATH:-}"
      - "ASTER__APIS__PELICAN__PORT=${ASTER__APIS__PELICAN__PORT:-10200}"
      - "ASTER__APIS__PELICAN__SCHEME=${ASTER__APIS__PELICAN__SCHEME:-http}"
      - "ASTER__DEBUG=${ASTER__DEBUG:-true}"
      - "ASTER__SERVER__HOST=${ASTER__SERVER__HOST:-0.0.0.0}"
      - "ASTER__SERVER__PORT=${ASTER__SERVER__PORT:-10110}"
    network_mode: host
